---
title: "GSE118959_circRNA"
author: "Barry"
date: "17/04/2020"
output: html_document
---

## Analysis comments

I do not know how to load the two channel raw data into R, so you must work with the log2 normalised series matrix provided by GEO. You cannot generate the raw intensity values due to decimal rounding by R (for small intensity values, the result will be really close. For larger values the lack of numbers after the decimal really shows). The code below perfectly recapitulates the results returned by Arraystar to the decimal in terms of normalised values, p-vales and FDR. While it would be nice to process the data myself, I think it is best to use the published results as this will stand up under peer review. 

### Functions for Results

```{R}
fold_change <- function(ratio){
  FC <- ifelse(ratio < 1, -1/ratio, ratio)
  return(FC)
}



```


```{R}
setwd("/data/github/GSE118959/data/")

mtx <- read.table("circrna/GSE118959_series_matrix.txt", sep="\t", header=T, row.names = "ID_REF")

renamed <- c("Control_1", "Control_2", "Control_3",
               "Clone1_1", "Clone1_2", "Clone1_3",
               "Clone9_1", "Clone9_2", "Clone9_3")

colnames(mtx) <- renamed
```


```{R}
for(i in 1:nrow(mtx)){
  
  row <- mtx[i,]
  
  control <- as.numeric(row[,1:3])
  clone1 <- as.numeric(row[,4:6])
  clone9 <- as.numeric(row[,7:9])
  
  t.test_clone1 <- t.test(clone1, control, paired=T)
  t.test_clone9 <- t.test(clone9, control, paired=T)
  
  clone1_p.val <- t.test_clone1$p.value
  clone9_p.val <- t.test_clone9$p.value
  
  clone1_ratio <- 2^((mean(clone1))-(mean(control)))
  clone9_ratio <- 2^((mean(clone9))-(mean(control)))
  
  mtx$Control_AvExp[i] <- mean(control)
  mtx$Clone1_AvExp[i] <- mean(clone1)
  mtx$Clone9_AvExp[i] <- mean(clone9)
  
  mtx$Clone1_FC[i] <- fold_change(clone1_ratio)
  mtx$Clone1_pvalue[i] <- clone1_p.val 
  
  mtx$Clone9_FC[i] <- fold_change(clone9_ratio)
  mtx$Clone9_pvalue[i] <- clone9_p.val
}

# Calculate FDR
mtx$Clone1_FDR <- p.adjust(mtx$Clone1_pvalue, method = "fdr")
mtx$Clone9_FDR <- p.adjust(mtx$Clone9_pvalue, method = "fdr")

```

# subset results to keep tidy
```{R}
# rownames are preserved.. 
clone1_res <- mtx[,c("Clone1_FC", "Clone1_pvalue", "Clone1_FDR")]
clone9_res <- mtx[,c("Clone9_FC", "Clone9_pvalue", "Clone9_FDR")]
```

# subset again
```{R}
up_key <-  intersect(rownames(clone9_res)[which(clone9_res$Clone9_FC>=2)],
                     rownames(clone9_res)[which(clone9_res$Clone9_pvalue<=0.05)])

down_key <- intersect(rownames(clone9_res)[which(clone9_res$Clone9_FC<=-2)],
                      rownames(clone9_res)[which(clone9_res$Clone9_pvalue<=0.05)])

up_key1 <-  intersect(rownames(clone1_res)[which(clone1_res$Clone1_FC>=2)],
                     rownames(clone1_res)[which(clone1_res$Clone1_pvalue<=0.05)])

down_key1 <- intersect(rownames(clone1_res)[which(clone1_res$Clone1_FC<=-2)],
                      rownames(clone1_res)[which(clone1_res$Clone1_pvalue<=0.05)])

clone1_upreg <- as.data.frame((clone1_res)[which(rownames(clone1_res) %in% up_key1),],)

clone1_downreg <- as.data.frame((clone1_res)[which(rownames(clone1_res) %in% down_key1),])

clone9_upreg <- as.data.frame((clone9_res)[which(rownames(clone9_res) %in% up_key),])

clone9_downreg <- as.data.frame((clone9_res)[which(rownames(clone9_res) %in% down_key),])

```

# add on the alias names (matches CSCD i think, just grep the dir to check ..)

```{R}
alias <- read.csv("/data/github/GSE118959/data/circrna/master_probe.csv", header=T, sep="\t")

mtx <- merge(mtx, alias, by.x="row.names", by.y="probeID")
```

# and clean. subset as you see fit downstream analyses.

```{R}
colnames(mtx)[1] = "Probe_ID"

order <- c("Probe_ID", "circRNA", "Alias", "GeneSymbol", "Control_AvExp", "Clone1_AvExp", "Clone1_FC", "Clone1_pvalue", "Clone1_FDR", "Control_AvExp", "Clone9_AvExp", "Clone9_FC", "Clone9_pvalue", "Clone9_FDR", "Control_1", "Control_2", "Control_3", "Clone1_1", "Clone1_2", "Clone1_3", "Clone9_1", "Clone9_2", "Clone9_3")

mtx <- mtx[,order]
```












clone1_upreg$probeID <- rownames(clone1_upreg)
clone1_upreg <- merge(clone1_upreg, alias, by="probeID")
rownames(clone1_upreg) <- clone1_upreg$probeID
clone1_upreg <- clone1_upreg[, c(5, 6, 8, 9, 10, 11, 2, 3, 4)]
clone1_upreg$strand <- "-"

## i used "-" for strand orientation in manually created bed file, must match here.

clone1_downreg$probeID <- rownames(clone1_downreg)
clone1_downreg <- merge(clone1_downreg, alias, by="probeID")
rownames(clone1_downreg) <- clone1_downreg$probeID
clone1_downreg <- clone1_downreg[, c(5, 6, 8, 9, 10, 11, 2, 3, 4)]
clone1_downreg$strand <- "-"

clone9_upreg$probeID <- rownames(clone9_upreg)
clone9_upreg <- merge(clone9_upreg, alias, by="probeID")
rownames(clone9_upreg) <- clone9_upreg$probeID
clone9_upreg <- clone9_upreg[, c(5, 6, 8, 9, 10, 11, 2, 3, 4)]
clone9_upreg$strand <- "-"

clone9_downreg$probeID <- rownames(clone9_downreg)
clone9_downreg <- merge(clone9_downreg, alias, by="probeID")
rownames(clone9_downreg) <- clone9_downreg$probeID
clone9_downreg <- clone9_downreg[, c(5, 6, 8, 9, 10, 11, 2, 3, 4)]
clone9_downreg$strand <- "-"

# add NA to empty cells
# convert to characters
# replace NA with adjacent circRNA ID 
# last answer no votes??? https://stackoverflow.com/questions/15629885/replace-na-in-column-with-value-in-adjacent-column

clone1_upreg[clone1_upreg==""] <- NA
clone1_upreg$circRNA <- as.character(clone1_upreg$circRNA)
clone1_upreg$Alias <- as.character(clone1_upreg$Alias)
clone1_upreg$Alias <- ifelse(is.na(clone1_upreg$Alias), paste(clone1_upreg$circRNA), paste(clone1_upreg$Alias)); clone1_upreg
write.table(clone1_upreg, file="results/DE_circRNA/clone1_upreg.txt", sep="\t", row.names = F, quote = F)

clone1_downreg[clone1_downreg==""] <- NA
clone1_downreg$circRNA <- as.character(clone1_downreg$circRNA)
clone1_downreg$Alias <- as.character(clone1_downreg$Alias)
clone1_downreg$Alias <- ifelse(is.na(clone1_downreg$Alias), paste(clone1_downreg$circRNA), paste(clone1_downreg$Alias)); clone1_downreg
write.table(clone1_downreg, file="results/DE_circRNA/clone1_downreg.txt", sep="\t", row.names = F, quote = F)

clone9_upreg[clone9_upreg==""] <- NA
clone9_upreg$circRNA <- as.character(clone9_upreg$circRNA)
clone9_upreg$Alias <- as.character(clone9_upreg$Alias)
clone9_upreg$Alias <- ifelse(is.na(clone9_upreg$Alias), paste(clone9_upreg$circRNA), paste(clone9_upreg$Alias)); clone9_upreg
write.table(clone9_upreg, file="results/DE_circRNA/clone9_upreg.txt", sep="\t", row.names = F, quote = F)

clone9_downreg[clone9_downreg==""] <- NA
clone9_downreg$circRNA <- as.character(clone9_downreg$circRNA)
clone9_downreg$Alias <- as.character(clone9_downreg$Alias)
clone9_downreg$Alias <- ifelse(is.na(clone9_downreg$Alias), paste(clone9_downreg$circRNA), paste(clone9_downreg$Alias)); clone9_downreg
write.table(clone9_downreg, file="results/DE_circRNA/clone9_downreg.txt", sep="\t", row.names = F, quote = F)
```



